### User Register
POST http://localhost:3000/user-api/users
Content-Type: application/json

{
    "firstName": "Sai",
    "lastName": "Pulla",
    "email":"sai@gmail.com",
    "password":"Sai123"
}

### User authenticate
POST http://localhost:3000/user-api/authenticate
Content-Type: application/json

{
    "email":"sai@gmail.com",
    "password":"Sai123",
    "role":"USER"
}




### Author Register
POST http://localhost:3000/author-api/users
Content-Type: application/json

{
    "firstName": "Raju",
    "lastName": "Pulla",
    "email":"raju@gmail.com",
    "password":"Rajui123"
}

### Author authenticate
POST http://localhost:3000/author-api/authenticate
Content-Type: application/json

{
    "email":"ravi@gmail.com",
    "password":"Ravi123",
    "role":"AUTHOR"
}

### Creating Article
POST http://localhost:3000/author-api/articles
Content-Type: application/json

{
    "author":"698967f2a92ba4dc5be7c966",
    "title":"test1 article",
    "category":"programming",
    "content":"test1 article content"
}

###Reading articles of the author
GET http://localhost:3000/author-api/articles/698979935d68a2bc37f9c04b

### Updating Article
PUT http://localhost:3000/author-api/articles
Content-Type: application/json

{
    "author":"698979935d68a2bc37f9c04b",
    "article":"69897fb5c0e6f3cb79cc65c9",
    "title":"test1 article Updated1",
    "category":"programming",
    "content":"test1 article content"
}